# Generated by Django 4.0.2 on 2022-02-24 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glptitle', models.CharField(max_length=250)),
                ('glpdescription', models.TextField()),
                ('eXoID', models.IntegerField()),
                ('LBID', models.CharField(max_length=250)),
                ('priority', models.CharField(max_length=10)),
                ('files', models.CharField(max_length=10)),
                ('batchname', models.CharField(max_length=250)),
                ('foldername', models.CharField(max_length=250)),
                ('box', models.CharField(max_length=10)),
                ('manual', models.CharField(max_length=10)),
                ('media', models.CharField(max_length=10)),
                ('iso', models.CharField(max_length=10)),
                ('comments', models.TextField()),
                ('version', models.CharField(max_length=250)),
                ('ineXoDOS', models.CharField(max_length=250)),
                ('variant', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('dosbox', models.CharField(max_length=250)),
                ('dosboxsound', models.CharField(max_length=250)),
                ('scummvm', models.CharField(max_length=250)),
                ('scummvmsound', models.CharField(max_length=250)),
                ('network', models.CharField(max_length=10)),
                ('tested', models.CharField(max_length=10)),
                ('cracked', models.CharField(max_length=10)),
                ('hasissues', models.CharField(max_length=10)),
                ('exception', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
