# Generated by Django 3.2.12 on 2022-02-25 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_glp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('media', models.CharField(choices=[('F3', 'Floppy 3,5"'), ('F5', 'Floppy 5,25"'), ('CD', 'CD-ROM'), ('DD', 'DVD-ROM'), ('DL', 'Download')], default='F3', max_length=2)),
                ('year', models.CharField(max_length=10)),
                ('speech', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('barcode', models.CharField(max_length=250)),
                ('usk', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.developer')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.publisher')),
            ],
        ),
    ]
