# Generated by Django 3.2.12 on 2022-02-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_developer_publisher_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='rlstitle',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
