# Generated by Django 3.2.12 on 2022-03-01 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_release_rlstitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glp',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glps', to='games.game'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfilename', models.ImageField(upload_to='images')),
                ('imgtype', models.CharField(choices=[('cvr', 'Front-Cover'), ('bck', 'Back-Cover'), ('med', 'Media'), ('oth', 'other...')], default='cvr', max_length=3)),
                ('imgdescr', models.CharField(max_length=250)),
                ('imgcomment', models.TextField()),
                ('imgrawfilename', models.CharField(max_length=250)),
                ('imgrawlink', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('rlstitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releasetitle', to='games.release')),
            ],
        ),
    ]
