# Generated by Django 3.2.12 on 2022-03-01 15:24

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_image_imgrawfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgcomment',
            field=models.TextField(verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgdescr',
            field=models.CharField(max_length=250, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgfilename',
            field=models.ImageField(upload_to=games.models.PathAndRename('images'), verbose_name='Bilddatei'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgrawfilename',
            field=models.ImageField(upload_to=games.models.PathAndRename('images_raw'), verbose_name='Roh-Bilddatei'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgrawlink',
            field=models.CharField(max_length=300, verbose_name='Link zu Rohscans'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgtype',
            field=models.CharField(choices=[('cvr', 'Front-Cover'), ('bck', 'Back-Cover'), ('med', 'Media'), ('oth', 'other...')], default='cvr', max_length=3, verbose_name='Bildtyp:'),
        ),
        migrations.AlterField(
            model_name='image',
            name='rlstitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releasetitle', to='games.release', verbose_name='Release'),
        ),
        migrations.AlterField(
            model_name='release',
            name='rlstitle',
            field=models.CharField(max_length=250, verbose_name='Release'),
        ),
    ]
