# Generated by Django 4.0.2 on 2022-03-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20220301_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgfilename',
            field=models.CharField(max_length=250, verbose_name='Bilddatei'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgrawfilename',
            field=models.CharField(max_length=250, verbose_name='Roh-Bilddatei'),
        ),
    ]
