# Generated by Django 3.2.12 on 2022-03-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_image_imgfilename_alter_image_imgrawfilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imgrawfilename',
        ),
        migrations.AlterField(
            model_name='image',
            name='imgfilename',
            field=models.CharField(default='https://timberserver.de/gddb/media/images/', max_length=250, verbose_name='Bilddatei'),
        ),
    ]
