# Generated by Django 3.2.12 on 2022-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20220302_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(default='Timber', max_length=300, verbose_name='Von wem ist das Bild'),
        ),
    ]
