# Generated by Django 3.2.12 on 2022-03-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgcomment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgdescr',
            field=models.CharField(blank=True, max_length=250, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgfilename',
            field=models.CharField(max_length=250, verbose_name='Bilddatei'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgrawlink',
            field=models.CharField(blank=True, max_length=300, verbose_name='Link zu Rohscans'),
        ),
    ]
