# Generated by Django 3.2.12 on 2022-03-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_disk'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imgrawfilename',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Roh-Bilddatei'),
        ),
    ]
