# Generated by Django 3.2.12 on 2022-03-02 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_image_imgrawfilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrafilename', models.CharField(max_length=250, verbose_name='Dateiname')),
                ('extratype', models.CharField(choices=[('MAN', 'Handbuch'), ('REF', 'Referenzkarte'), ('MAP', 'Karte/Poster'), ('REG', 'Registrationskarte'), ('HBK', 'Lösungsbuch'), ('OTH', 'Download')], default='MAN', max_length=3, verbose_name='Extra-Typ:')),
                ('extrarawfilename', models.CharField(blank=True, default='', max_length=250, verbose_name='Roh-Scandateien')),
                ('extralanguage', models.CharField(default='de', max_length=250, verbose_name='Sprache(n)')),
                ('extrapages', models.IntegerField(verbose_name='Anzahl Seiten')),
                ('extraquality', models.IntegerField(verbose_name='Qualität')),
                ('extradescr', models.CharField(blank=True, max_length=250, verbose_name='Beschreibung')),
                ('extracomment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('extrasource', models.CharField(default='Timber', max_length=300, verbose_name='Von wem ist der Scan')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('rlstitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releasetitle3', to='games.release', verbose_name='Release')),
            ],
        ),
    ]
