# Generated by Django 3.2.12 on 2022-03-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='extratypedescr',
            field=models.CharField(blank=True, max_length=250, verbose_name='Typ Beschreibung'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='extratype',
            field=models.CharField(choices=[('MAN', 'Handbuch'), ('REF', 'Referenzkarte'), ('MAP', 'Karte/Poster'), ('REG', 'Registrationskarte'), ('HBK', 'Lösungsbuch'), ('OTH', 'other...')], default='MAN', max_length=3, verbose_name='Extra-Typ:'),
        ),
    ]
