# Generated by Django 3.2.12 on 2022-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20220302_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mobygameslink',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='game',
            name='ogdblink',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
