# Generated by Django 3.2.12 on 2022-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20220302_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='ogdblink',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
