# Generated by Django 3.2.12 on 2022-03-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_release_ogdblink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='extrarawfilename',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imgrawfilename',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imgrawlink',
        ),
        migrations.AddField(
            model_name='release',
            name='archivelink',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Eintrags auf archive.org'),
        ),
        migrations.AddField(
            model_name='release',
            name='coverfilename',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Cover-Dateiname'),
        ),
        migrations.AddField(
            model_name='release',
            name='platform',
            field=models.CharField(choices=[('DOS', 'MS-DOS'), ('W3X', 'Windows 3x'), ('W9X', 'Windows 9x'), ('WXX', 'Windows')], default='DOS', max_length=3),
        ),
        migrations.AddField(
            model_name='release',
            name='rawfile',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Raw-Files Dateiname'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='disktype',
            field=models.CharField(choices=[('F35', 'Floppy 3,5"'), ('F35K', 'Floppy 3,5" (Kryoflux)'), ('F52', 'Floppy 5,25"'), ('F52K', 'Floppy 5,25" (Kryoflux'), ('CDR', 'CD-ROM'), ('DVD', 'DVD-ROM'), ('DDL', 'Download')], default='F35', max_length=4, verbose_name='Medientyp:'),
        ),
        migrations.AlterField(
            model_name='release',
            name='barcode',
            field=models.CharField(max_length=250, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='release',
            name='ogdblink',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Link zu OGDB'),
        ),
        migrations.AlterField(
            model_name='release',
            name='speech',
            field=models.CharField(max_length=250, verbose_name='Sprachausgabe'),
        ),
        migrations.AlterField(
            model_name='release',
            name='text',
            field=models.CharField(max_length=250, verbose_name='Textsprachen'),
        ),
        migrations.AlterField(
            model_name='release',
            name='usk',
            field=models.CharField(max_length=100, verbose_name='USK-Freigabe'),
        ),
        migrations.AlterField(
            model_name='release',
            name='year',
            field=models.CharField(max_length=10, verbose_name='Veröffentlichungsjahr'),
        ),
    ]
