# Generated by Django 4.0.2 on 2022-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20220309_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='timberown',
            field=models.BooleanField(default=False, verbose_name='Im Besitz'),
        ),
        migrations.AddField(
            model_name='extra',
            name='timberown',
            field=models.BooleanField(default=False, verbose_name='Im Besitz'),
        ),
        migrations.AddField(
            model_name='release',
            name='timberown',
            field=models.BooleanField(default=False, verbose_name='Im Besitz'),
        ),
    ]
