# Generated by Django 4.0.2 on 2022-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_disk_timberown_extra_timberown_release_timberown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='extraquality',
        ),
        migrations.AddField(
            model_name='disk',
            name='quali',
            field=models.CharField(choices=[('1', '1 - Gut'), ('2', '2 - Ausreichend'), ('3', '3 - Schlecht')], default='1', max_length=1, verbose_name='Qualität:'),
        ),
        migrations.AddField(
            model_name='disk',
            name='timbercomment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='disk',
            name='timberquali',
            field=models.CharField(choices=[('1', '1 - Gut'), ('2', '2 - Ausreichend'), ('3', '3 - Schlecht')], default='1', max_length=1, verbose_name='Qualität:'),
        ),
        migrations.AddField(
            model_name='extra',
            name='extraquali',
            field=models.CharField(choices=[('1', '1 - Gut'), ('2', '2 - Ausreichend'), ('3', '3 - Schlecht')], default='1', max_length=1, verbose_name='Qualität:'),
        ),
        migrations.AddField(
            model_name='extra',
            name='timbercomment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='extra',
            name='timberquali',
            field=models.CharField(choices=[('1', '1 - Gut'), ('2', '2 - Ausreichend'), ('3', '3 - Schlecht')], default='1', max_length=1, verbose_name='Qualität:'),
        ),
        migrations.AddField(
            model_name='image',
            name='imgquali',
            field=models.CharField(choices=[('1', '1 - Gut'), ('2', '2 - Ausreichend'), ('3', '3 - Schlecht')], default='1', max_length=1, verbose_name='Qualität:'),
        ),
        migrations.AddField(
            model_name='image',
            name='timbercomment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='image',
            name='timberown',
            field=models.BooleanField(default=False, verbose_name='Im Besitz'),
        ),
        migrations.AddField(
            model_name='image',
            name='timberquali',
            field=models.CharField(choices=[('1', '1 - Gut'), ('2', '2 - Ausreichend'), ('3', '3 - Schlecht')], default='1', max_length=1, verbose_name='Qualität:'),
        ),
        migrations.AddField(
            model_name='release',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='release',
            name='quali',
            field=models.CharField(choices=[('1', '1 - Gut'), ('2', '2 - Ausreichend'), ('3', '3 - Schlecht')], default='1', max_length=1, verbose_name='Qualität:'),
        ),
        migrations.AddField(
            model_name='release',
            name='timbercomment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='release',
            name='timberquali',
            field=models.CharField(choices=[('1', '1 - Gut'), ('2', '2 - Ausreichend'), ('3', '3 - Schlecht')], default='1', max_length=1, verbose_name='Qualität:'),
        ),
    ]
