# Generated by Django 4.0.2 on 2022-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_remove_image_timbercomment_remove_image_timberown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='diskfilename',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Image-Datei der Medien'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='extrafilename',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Dateiname'),
        ),
    ]
