# Generated by Django 4.0.2 on 2022-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_alter_disk_diskfilename_alter_extra_extrafilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='source',
            field=models.CharField(blank=True, default='Timber', max_length=300, verbose_name='Von wem ist der Rip'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='extrasource',
            field=models.CharField(blank=True, default='Timber', max_length=300, verbose_name='Von wem ist der Scan'),
        ),
    ]
