# Generated by Django 4.0.2 on 2022-03-14 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_alter_disk_source_alter_extra_extrasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformname', models.CharField(blank=True, default='', max_length=250, verbose_name='Name')),
                ('platformshort', models.CharField(blank=True, default='', max_length=250, verbose_name='Abkürzung')),
                ('platformdescr', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('platformimgfilename', models.CharField(blank=True, default='', max_length=250, verbose_name='Logo')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='release',
            name='platform',
        ),
    ]
