# Generated by Django 4.0.2 on 2022-03-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_platform_remove_release_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='platformlnk',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='games.platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platformname',
            field=models.CharField(default='', max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platformshort',
            field=models.CharField(default='', max_length=250, verbose_name='Abkürzung'),
        ),
    ]
