# Generated by Django 4.0.2 on 2022-03-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_release_platformlnk_alter_platform_platformname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='quali',
        ),
    ]
