# Generated by Django 4.0.2 on 2022-03-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_remove_release_quali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='extratype',
            field=models.CharField(choices=[('MAN', 'Handbuch'), ('REF', 'Referenzkarte'), ('MAP', 'Karte/Poster'), ('REG', 'Registrationskarte'), ('HBK', 'Lösungsbuch'), ('CDW', 'Code-Wheel'), ('OTH', 'other...')], default='MAN', max_length=3, verbose_name='Extra-Typ:'),
        ),
    ]
