# Generated by Django 3.2.12 on 2022-04-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_alter_extra_extratype'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='eXoID',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='release',
            name='addon',
            field=models.BooleanField(default=False, verbose_name='Addon?'),
        ),
    ]
