# Generated by Django 3.2.12 on 2022-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_release_timberprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='timberbuydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
