# Generated by Django 3.2.12 on 2022-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_release_timberbuydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='timberbuydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
