# Generated by Django 3.2.12 on 2023-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_alter_release_timberbuydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='toEulisker',
            field=models.BooleanField(default=False, verbose_name='Eulisker?'),
        ),
        migrations.AddField(
            model_name='release',
            name='toEuliskerComment',
            field=models.TextField(blank=True, verbose_name='Hinweis Eulisker'),
        ),
    ]
