# Generated by Django 3.2.12 on 2023-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_auto_20230305_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='toEuliskerArchivelink',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Eulisker-Eintrag auf archive.org'),
        ),
        migrations.AlterField(
            model_name='release',
            name='archivelink',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Eintrag auf archive.org'),
        ),
    ]
