# Generated by Django 4.0.2 on 2023-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_auto_20230315_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='timberbuycomment',
            field=models.TextField(blank=True, verbose_name='Kauf/Verkauf Info'),
        ),
    ]
