# Generated by Django 4.0.2 on 2023-03-31 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_alter_disk_disktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='titles',
            field=models.ManyToManyField(related_name='gametitle', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_title', to='games.game'),
        ),
    ]
