# Generated by Django 4.0.2 on 2023-03-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_release_titles_alter_release_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='title',
        ),
    ]
