# Generated by Django 4.0.2 on 2023-04-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_release_i3dbox_release_i3dboxlower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='i3dbox',
            field=models.BooleanField(default=False, verbose_name='3D Box'),
        ),
        migrations.AlterField(
            model_name='release',
            name='i3dboxlower',
            field=models.BooleanField(default=False, verbose_name='3D Box untere Hälfte'),
        ),
        migrations.AlterField(
            model_name='release',
            name='i3dboxupper',
            field=models.BooleanField(default=False, verbose_name='3D Box obere Hälfte'),
        ),
        migrations.AlterField(
            model_name='release',
            name='i3djewelcase',
            field=models.BooleanField(default=False, verbose_name='3D Jewelcase'),
        ),
    ]
