# Generated by Django 4.0.2 on 2023-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0044_alter_release_i3dbox_alter_release_i3dboxlower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='disktype',
            field=models.CharField(choices=[('F35', 'Floppy 3,5"'), ('F35K', 'Floppy 3,5" (Kryoflux)'), ('F52', 'Floppy 5,25"'), ('F52K', 'Floppy 5,25" (Kryoflux)'), ('CDR', 'CD-ROM'), ('DVD', 'DVD-ROM'), ('DDL', 'Download'), ('TAPE', 'Tape')], default='F35', max_length=4, verbose_name='Medientyp:'),
        ),
    ]
