# Generated by Django 4.0.2 on 2023-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_alter_release_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='rlsregion',
            field=models.CharField(choices=[('DACH', 'Deutschland/DACH'), ('US', 'USA'), ('UK', 'Great Britain/UK')], default='DACH', max_length=4),
        ),
    ]
