# Generated by Django 5.0.2 on 2024-03-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0048_release_timbersold_release_timbersolddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='boxdepth',
            field=models.CharField(default='0', max_length=100, verbose_name='Box - Tiefe'),
        ),
        migrations.AddField(
            model_name='release',
            name='boxheight',
            field=models.CharField(default='0', max_length=100, verbose_name='Box - Länge'),
        ),
        migrations.AddField(
            model_name='release',
            name='boxwidth',
            field=models.CharField(default='0', max_length=100, verbose_name='Box - Breite'),
        ),
    ]
