# Generated by Django 5.0.2 on 2024-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0049_release_boxdepth_release_boxheight_release_boxwidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='scancomplete',
            field=models.BooleanField(default=False, verbose_name='Scan komplett?'),
        ),
    ]
