# Generated by Django 4.2.11 on 2024-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0050_release_scancomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='launchboxID',
            field=models.CharField(default='', max_length=100, verbose_name='LaunchBox-ID'),
        ),
    ]
